version: "3.8"
services:
    web:
      build: ./frontend
      ports:
        - 3000:3000
    api:
      build: ./backend
      ports:
        - 8000:8000
    db:
      image: mysql:latest
      ports: 
        - 3306:3306